language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=WeConnect_RestAPI/tests
  - coveralls

after_success:
  - "coveralls"